FROM --platform=$BUILDPLATFORM golang:1.19-alpine AS builder

# Move to working directory (/build).
WORKDIR /build

ENV CGO_ENABLED=0

# Copy and download dependency using go mod.
COPY go.mod go.sum ./
RUN go mod download

# Copy the code into the container.
COPY ./consumer/main.go .

# Set necessary environment variables needed
# for our image and build the consumer.
ARG TARGETOS
ARG TARGETARCH

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build \
    -ldflags='-w -s' -a \
    -o consumer .

FROM scratch

# Copy binary and config files from /build
# to root folder of scratch container.
COPY --from=builder ["/build/consumer", "/"]

# Command to run when starting the container.
ENTRYPOINT ["/consumer"]